2016-12-29 16:31:54,590 [ERROR] django.request: Internal Server Error: /contact_form/
Traceback (most recent call last):
  File "/Users/atrig001/Desktop/sites/highplains-site/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/atrig001/Desktop/sites/highplains-site/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view woodapp.views.contact_form didn't return an HttpResponse object. It returned None instead.
2016-12-29 16:31:57,568 [ERROR] django.request: Internal Server Error: /contact_form/
Traceback (most recent call last):
  File "/Users/atrig001/Desktop/sites/highplains-site/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/atrig001/Desktop/sites/highplains-site/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view woodapp.views.contact_form didn't return an HttpResponse object. It returned None instead.
2016-12-29 16:32:01,730 [ERROR] django.request: Internal Server Error: /contact_form/
Traceback (most recent call last):
  File "/Users/atrig001/Desktop/sites/highplains-site/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/atrig001/Desktop/sites/highplains-site/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view woodapp.views.contact_form didn't return an HttpResponse object. It returned None instead.
2016-12-29 16:32:38,163 [WARNING] django.request: Not Found: /contact/
2016-12-29 16:32:38,832 [ERROR] django.request: Internal Server Error: /contact_form/
Traceback (most recent call last):
  File "/Users/atrig001/Desktop/sites/highplains-site/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/atrig001/Desktop/sites/highplains-site/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view woodapp.views.contact_form didn't return an HttpResponse object. It returned None instead.
2016-12-29 16:32:40,208 [ERROR] django.request: Internal Server Error: /contact_form/
Traceback (most recent call last):
  File "/Users/atrig001/Desktop/sites/highplains-site/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/atrig001/Desktop/sites/highplains-site/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view woodapp.views.contact_form didn't return an HttpResponse object. It returned None instead.
2016-12-29 16:33:21,026 [ERROR] django.request: Internal Server Error: /contact_form/
Traceback (most recent call last):
  File "/Users/atrig001/Desktop/sites/highplains-site/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/atrig001/Desktop/sites/highplains-site/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view woodapp.views.contact_form didn't return an HttpResponse object. It returned None instead.
